# Generated by Django 5.1.6 on 2025-03-14 13:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodereader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturerprofile',
            name='Business_licence',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
