# Generated by Django 5.1.6 on 2025-03-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodereader', '0005_alter_manufacturerprofile_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
