# Generated by Django 5.1.6 on 2025-03-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodereader', '0008_barcode_barcode_image_barcode_qr_code_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_of_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
